locals {
  environment_vars = read_terragrunt_config(find_in_parent_folders("env.hcl"))
  environment      = local.environment_vars.locals.environment

  keycloak_url = get_env("KEYCLOAK_URL", "http://keycloak.k3s.prod")
}

terraform {
  source = "../../../../../../devops-terraform-modules//on-prem/shared/keycloak"
}

# SHARED-PLATFORM PROD (2026-08-02, [[production-cloudflare-tunnel]] Phase 1): prod REUSES local's
# Keycloak + the shared `fitmate` realm — it does NOT provision its own. ALWAYS excluded (re-creating
# the realm on the same Keycloak would collide with local). Prod realm/hostname changes (Phase 5:
# un-pin KC hostname / add auth.fitmate.me frontend URL) are made in LOCAL's keycloak unit, not here.
exclude {
  if      = true
  actions = ["all"]
}

dependency "vault-secrets" {
  config_path = "../../vault-secrets"
  mock_outputs = {
    secrets = {
      "keycloak/fitmate/trainee1/creds" = { username = "trainee1", password = "MOCK" }
    }
  }
  # plan/validate may use mocks (fills a newly-added sub-key); apply requires real applied outputs.
  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan"]
  mock_outputs_merge_strategy_with_state  = "deep_map_only"
}

include "root" {
  path = find_in_parent_folders("root.hcl")
}

include "keycloak" {
  path = find_in_parent_folders("keycloak.hcl")
}

inputs = {
  keycloak_url = local.keycloak_url

  realm = {
    name         = "fitmate"
    enabled      = true
    display_name = "FITMate"
    ssl_required = "none" # HTTP lab: Keycloak reached at http://keycloak.k3s.prod via Traefik

    # Services gate on realm_access.roles.
    # NOTE: role is "administrator", NOT "admin" — Keycloak 26.4.0+ has an FGAP regression that blocks
    # updating a realm role literally named "admin" (403), even for a super-admin. The FitMate services
    # must gate on `administrator` in realm_access.roles. (keycloak/keycloak#43579, #44371)
    roles = ["trainee", "trainer", "administrator", "super_admin"]

    clients = [
      {
        client_id                       = "fitmate-website"
        name                            = "FITMate Website (BFF)"
        access_type                     = "CONFIDENTIAL" # issues a client_secret (Auth.js BFF holds it)
        standard_flow_enabled           = true           # Authorization Code
        direct_access_grants_enabled    = false
        pkce_code_challenge_method      = "S256"
        valid_redirect_uris             = ["http://localhost:3000/api/auth/callback/keycloak"]
        valid_post_logout_redirect_uris = ["http://localhost:3000"]
        web_origins                     = ["http://localhost:3000"]
        # CRITICAL: backend services require aud contains fitmate-backend (Keycloak default aud = account).
        audiences = ["fitmate-backend"]
      },
    ]

    # e2e test user. firstName/lastName/email/email_verified are REQUIRED for a password-grant
    # fixture — Keycloak 26's declarative user profile otherwise triggers VERIFY_PROFILE at login and
    # the direct grant fails with "Account is not fully set up" (with an empty requiredActions list).
    users = [
      {
        username       = "trainee1"
        email          = "trainee1@fitmate.local"
        first_name     = "Trainee"
        last_name      = "One"
        email_verified = true
        realm_roles    = ["trainee"]
      },
    ]
  }

  # trainee1 password from Vault (generated by vault-secrets).
  user_passwords = {
    trainee1 = dependency.vault-secrets.outputs.secrets["keycloak/fitmate/trainee1/creds"]["password"]
  }

  # Hand the GENERATED fitmate-website secret straight to Vault → ESO → website (no manual copy).
  # mount must match the vault-auths KV mount (the org). path mirrors the local/<svc>/creds layout.
  vault_push = {
    enabled = true
    mount   = "fitmate"
    clients = {
      "fitmate-website" = { path = "local/website/creds", key = "AUTH_KEYCLOAK_SECRET" }
    }
  }
}
