#!/bin/bash

set -euo pipefail

export QUERY_SERVICE_PORT=${QUERY_SERVICE_PORT:-8061}
export QUERY_SERVICE_NAME=${QUERY_SERVICE_NAME:-"QUERY-OCI"}
export QUERY_SERVICE_TIME_INTERVAL=${QUERY_SERVICE_TIME_INTERVAL:-"QUERY-OCI"}
export QUERY_SERVICE_OPN_LEGACY_ORG=${QUERY_SERVICE_OPN_LEGACY_ORG:-"Intersil"}
export QUERY_SERVICE_MATERIAL_LEGACY_ORG=${QUERY_SERVICE_MATERIAL_LEGACY_ORG:-"Intersil"}
export JAVA_OPS_XMS=${JAVA_OPS_XMS:-"-Xms128m -Xmx3g"}
