#!/bin/bash

set -euo pipefail

export HIKARI_MAXIMUM_POOL_SIZE=${HIKARI_MAXIMUM_POOL_SIZE:-50}
export HIKARI_MINIMUM_IDLE=${HIKARI_MINIMUM_IDLE:-2}
export HIKARI_CONNECTION_TIMEOUT=${HIKARI_CONNECTION_TIMEOUT:-20000}
export HIKARI_MAX_LIFE_TIME=${HIKARI_MAX_LIFE_TIME:-120000}
export HIKARI_POOL_NAME=${HIKARI_POOL_NAME:-"Poll-Query"}
