LDAP_PROVIDER_BIND_CREDENTIAL="admin_pass"
LDAP_PROVIDER_BIND_DN="cn=admin,dc=nthedao,dc=info"
LDAP_PROVIDER_USERS_DN="cn=dev,ou=users,dc=nthedao,dc=info"
LDAP_PROVIDER_USER_OBJECT_CLASSES="inetOrgPerson,posixAccount,top,organizationalPerson,person"
