# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    terraform {
      required_version = "~> 1.9.0"

      required_providers {
        helm = {
          source  = "hashicorp/helm"
          version = "~> 2.15.0"
        }
        kubernetes = {
          source  = "hashicorp/kubernetes"
          version = "~> 2.25.0"
        }
        kubectl = {
          source  = "gavinbunney/kubectl"
          version = "~> 1.14.0"
        }
      }
    }
