QUERY_SERVICE_PORT=8061
QUERY_SERVICE_NAME="QUERY-OCI"
QUERY_SERVICE_TIME_INTERVAL="QUERY-OCI"
QUERY_SERVICE_OPN_LEGACY_ORG="QUERY-OCI"
QUERY_SERVICE_MATERIAL_LEGACY_ORG="QUERY-OCI"
JAVA_OPS_XMS="-Xms128m -Xmx3g"

QUERY_SERVICE_DB_URL="corpagldbdv3.corp.idt.com"
QUERY_SERVICE_DB_PORT=1521
QUERY_SERVICE_DB_SID="agldev"
QUERY_SERVICE_DB_JDBC_CONNECTION_STRING="jdbc:oracle:thin:@${QUERY_SERVICE_DB_URL}:${QUERY_SERVICE_DB_PORT}:${QUERY_SERVICE_DB_SID}"
QUERY_SERVICE_DB_USERNAME="agile"
QUERY_SERVICE_DB_PASSWORD="a9ile4idT"
