AGILE_DB_URL="optagiledb001d.opt.renesas.com"
AGILE_DB_SID="DEV"
AGILE_DB_PORT=1521
AGILE_DB_JDBC_CONNECTION_STRING="jdbc:oracle:thin:@${AGILE_DB_URL}:${AGILE_DB_PORT}:${AGILE_DB_SID}"
AGILE_DB_USERNAME="agiledev"
AGILE_DB_PASSWORD="Agile#2024.Dev"
