#!/bin/bash

set -euo pipefail

export QUERY_SERVICE_PORT=${QUERY_SERVICE_PORT:-8061}
export QUERY_SERVICE_NAME=${QUERY_SERVICE_NAME:-"QUERY-OCI"}
export QUERY_SERVICE_TIME_INTERVAL=${QUERY_SERVICE_TIME_INTERVAL:-"QUERY-OCI"}
export QUERY_SERVICE_OPN_LEGACY_ORG=${QUERY_SERVICE_OPN_LEGACY_ORG:-"Intersil"}
export QUERY_SERVICE_MATERIAL_LEGACY_ORG=${QUERY_SERVICE_MATERIAL_LEGACY_ORG:-"Intersil"}
export JAVA_OPS_XMS=${JAVA_OPS_XMS:-"-Xms128m -Xmx3g"}

export AGILE_DB_URL=${AGILE_DB_URL:-"optagiledb001d.opt.renesas.com"}
export AGILE_DB_SID=${AGILE_DB_SID:-"DEV"}
export AGILE_DB_PORT=${AGILE_DB_PORT:-1521}
export AGILE_DB_JDBC_CONNECTION_STRING="jdbc:oracle:thin:@${AGILE_DB_URL}:${AGILE_DB_PORT}:${AGILE_DB_SID}"
export AGILE_DB_USERNAME=${AGILE_DB_USERNAME:-"agiledev"}
export AGILE_DB_PASSWORD=${AGILE_DB_PASSWORD:-"Agile#2024.Dev"}

export AGILE_APP_PORT=${AGILE_APP_PORT:-7001}
export AGILE_APP_URL=${AGILE_APP_URL:-"http://optagileapp001d.adwin.renesas.com:${AGILE_APP_PORT}/Agile"}
export AGILE_APP_USERNAME=${AGILE_APP_USERNAME:-"admin"}
export AGILE_APP_PASSWORD=${AGILE_APP_USERNAME:-"Agile#321#Dev"}

export QUERY_SERVICE_DB_URL=${QUERY_SERVICE_DB_URL:-"corpagldbdv3.corp.idt.com"}
export QUERY_SERVICE_DB_PORT=${QUERY_SERVICE_DB_PORT:-1521}
export QUERY_SERVICE_DB_SID=${QUERY_SERVICE_DB_SID:-"agldev"}
export QUERY_SERVICE_DB_JDBC_CONNECTION_STRING="jdbc:oracle:thin:@${QUERY_SERVICE_DB_URL}:${QUERY_SERVICE_DB_PORT}:${QUERY_SERVICE_DB_SID}"
export QUERY_SERVICE_DB_USERNAME=${QUERY_SERVICE_DB_USERNAME:-"agile"}
export QUERY_SERVICE_DB_PASSWORD=${QUERY_SERVICE_DB_PASSWORD:-"a9ile4idT"}
